language: "pt-BR"

reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  request_changes_workflow: false
  auto_review:
    enabled: true
    drafts: false
